spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:
    user:
      path: /user/**
      serviceId: user-service
      sensitiveHeaders: "*"
    hi:
      path: /hi/**
      serviceId: hi-service
      sensitiveHeaders: "*"
server:
  port: 10006