eureka:
  client:
    service-url:
      dafault_zone: localhost:8761/eureka
server:
  port: 10001

spring:
  application:
    name: user-service
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456

