eureka:
  client:
    service-url:
      dafault_zone: localhost:8761/eureka
server:
  port: 10003
spring:
  application:
    name: hi-service
  redis:
#    database: 0
#    host: localhost
#    port: 6379
    password: 123456
#
r:
  pA: 1
  pB: 4